#!/bin/bash

export PKGS=(
    bat
    bluez-utils
    curl
    diff-so-fancy
    dunst
    feh
    lsd
    neofetch
    nerd-fonts-fira-code
    pulsemixer
    tldr
    tree
    unzip
    xclip
    franz
    neovim
    polybar
    screenkey
    compton
    watchexec
    ack
    acpi
    acpi_call
    acpid
    alsa-tools
    alsa-utils
    android-udev
    anki
    antlr4
    arandr
    arc-gtk-theme
    arc-icon-theme
    arch-install-scripts
    ario
    artikulate
    atom
    audacity
    autoconf
    automake
    awesome
    awesome-terminal-fonts
    bash
    basket
    bbswitch
    bc
    bear
    binutils
    bison
    blender
    blender-plugin-animation-nodes-git
    blinken
    blueman
    bluez
    boost
    bullet
    bullet-docs
    bzip2
    calibre
    cantor
    cgal
    chromium
    clevo-xsm-wmi
    cmake
    codespell
    coreutils
    cppreference-devhelp
    cryptsetup
    ctags
    devhelp
    device-mapper
    dhcpcd
    dialog
    diffutils
    discord
    dmenu
    dotnet-sdk
    doxygen
    e2fsprogs
    efibootmgr
    eigen
    fakeroot
    feh
    file
    file-roller
    filelight
    filesystem
    findutils
    firefox
    flex
    flint
    fortune-mod
    fzf
    gawk
    gcc
    gcc-libs
    gcompris-qt
    gdal
    gdb
    genie-git
    gettext
    ghex
    gimp
    git
    git-lfs
    gitg
    gitkraken
    glibc
    gnome-latex
    gnome-screenshot
    gnome-system-monitor
    gnuplot
    godot
    goldendict
    gperftools
    graphviz
    grep
    grub
    gst-plugins-bad
    gst-plugins-good
    gst-python
    gst-python2
    gtk-theme-switch2
    gv
    gvim
    gzip
    hardinfo
    hexchat
    hid-tools
    hotspot
    hsetroot
    htop
    hugin
    hwinfo
    i3-gaps
    i3lock-color
    i3status
    inetutils
    inkscape
    inotify-tools
    intel-ucode
    iproute2
    iputils
    ispell
    jfsutils
    jq
    jupyterlab
    kalgebra
    kalzium
    kanagram
    kbruch
    kcachegrind
    kdeconnect
    kdeedu-meta
    kdoctools
    keepassxc
    kgeography
    khangman
    kig
    kiten
    kitty
    klettres
    kmplot
    krita
    ktouch
    kturtle
    kvantum-qt5
    kvantum-theme-arc
    kwordquiz
    less
    lib32-alsa-plugins
    lib32-glew
    lib32-libpulse
    lib32-nvidia-utils
    licenses
    light
    linux
    linux-docs
    linux-firmware
    linux-headers
    llvm
    lmms
    logrotate
    lshw
    luarocks
    luminancehdr
    lvm2
    lxappearance
    m4
    maim
    make
    man-db
    man-pages
    marble
    mdadm
    meld
    minecraft-launcher
    minuet
    moka-icon-theme
    mono
    mpc
    mpd
    mplayer
    mpv
    mupdf
    musescore
    nano
    nasm
    ncmpc
    ncmpcpp
    ncurses5-compat-libs
    nerd-fonts-git
    net-tools
    netctl
    network-manager-applet
    networkmanager
    ninja
    noto-fonts-cjk
    npm
    numlockx
    nvclock
    nvidia
    nvidia-prime
    nvidia-settings
    nvidia-utils
    nvidia-xrun
    openscenegraph
    openssh
    opentoonz
    oprofile
    os-prober
    p7zip
    pacman
    pacman-contrib
    pacutils
    pamac-aur
    pandoc
    pandoc-citeproc
    pandoc-crossref
    parley
    pasystray
    patch
    pavucontrol
    pciutils
    perf
    perl
    picom
    pidgin
    pidgin-sipe
    pkgconf
    playerctl
    plib
    polybar
    pork
    powerline
    powerline-fonts
    procps-ng
    psmisc
    pulseaudio
    pulseaudio-alsa
    pulseaudio-bluetooth
    python-breathe
    python-gitpython
    python-matplotlib
    python-pip
    python-ply
    python-powerline
    python-pybullet
    python-pyqt5
    python-scikit-learn
    python-scipy
    python-sphinx
    python-sympy
    qbittorrent
    qcachegrind
    qt5-charts
    qt5-connectivity
    qt5-doc
    qt5-examples
    qt5-styleplugins
    qt5-websockets
    qtcreator
    qwt
    radare2
    radare2-cutter
    ranger
    redshift
    reflector
    reiserfsprogs
    rmlint
    rocs
    rofi
    rosegarden
    s-nail
    sed
    shadow
    skypeforlinux-stable-bin
    sourcetrail
    spyder
    sqlitebrowser
    steam
    step
    sudo
    surf
    sysfsutils
    systemd-sysvcompat
    tabbed
    tar
    telegram-desktop
    terminus-font
    texinfo
    texlive-bibtexextra
    texlive-core
    texlive-fontsextra
    texlive-formatsextra
    texlive-games
    texlive-humanities
    texlive-latexextra
    texlive-music
    texlive-pictures
    texlive-pstricks
    texlive-publishers
    texlive-science
    texturepacker
    the_silver_searcher
    thunar
    thunderbird
    tmux
    tor-browser
    translate-shell
    ttf-anka-coder
    ttf-dejavu
    ttf-droid
    ttf-fantasque-sans-mono
    ttf-font-awesome
    ttf-liberation
    ttf-linux-libertine
    ttf-material-icons-git
    ttf-roboto
    ttf-typicons
    ttf-ubuntu-font-family
    unityhub
    unrar
    usbutils
    util-linux
    vala
    valgrind
    vi
    virtualbox
    virtualbox-ext-oracle
    virtualbox-guest-iso
    virtualbox-host-modules-arch
    visual-studio-code-bin
    vulkan-extra-layers
    vulkan-headers
    vulkan-html-docs
    vulkan-tools
    vulkan-validation-layers
    warsaw-bin
    weechat
    wget
    which
    wine
    write_stylus
    xf86-input-wacom
    xfce4-terminal
    xfsprogs
    xorg-bdftopcf
    xorg-fonts-type1
    xorg-iceauth
    xorg-luit
    xorg-mkfontscale
    xorg-server
    xorg-server-xephyr
    xorg-sessreg
    xorg-setxkbmap
    xorg-smproxy
    xorg-x11perf
    xorg-xbacklight
    xorg-xcmsdb
    xorg-xcursorgen
    xorg-xdpyinfo
    xorg-xdriinfo
    xorg-xev
    xorg-xgamma
    xorg-xhost
    xorg-xinit
    xorg-xinput
    xorg-xkbcomp
    xorg-xkbevd
    xorg-xkbutils
    xorg-xkill
    xorg-xlsatoms
    xorg-xlsclients
    xorg-xpr
    xorg-xprop
    xorg-xrandr
    xorg-xrefresh
    xorg-xset
    xorg-xsetroot
    xorg-xvinfo
    xorg-xwd
    xorg-xwininfo
    xorg-xwud
    xournalpp
    xsettingsd
    xss-lock
    yay
    zathura
    zathura-cb
    zathura-djvu
    zathura-pdf-mupdf
    zathura-ps
    zotero
)

